### ISSUE TITLE
esx_hud (global 'HUD') (global 'Config') 1.07

### ISSUE THREAD

**Issue by Tompizza** [esx-framework/esx_hud#12]
esx_hud (global 'HUD') (global 'Config') 1.07

[      script:esx_hud] Error loading script server/main.lua in resource esx_hud: @esx_hud/server/main.lua:1: attempt to index a nil value (global 'HUD')
[      script:esx_hud] stack traceback:
[      script:esx_hud]  @esx_hud/server/main.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[      script:esx_hud] Error loading script server/mileage.lua in resource esx_hud: @esx_hud/server/mileage.lua:1: attempt to index a nil value (global 'Config')
[      script:esx_hud] stack traceback:
[      script:esx_hud]  @esx_hud/server/mileage.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/mileage.lua.

**Comment by Rav3n95** [comment]
Fixed
