### ISSUE TITLE
Missing eof on shared folder main.lua + initiate esx on server side main.lua

### ISSUE THREAD

**Issue by krasher023** [esx-framework/esx_hud#13]
[      script:esx_hud] Error parsing script @esx_hud/shared/main.lua in resource esx_hud: @esx_hud/shared/main.lua:5: '}' expected (to close '{' at line 2) near <eof>
[    c-scripting-core] Failed to load script shared/main.lua.
[      script:esx_hud] Error loading script server/main.lua in resource esx_hud: @esx_hud/server/main.lua:1: attempt to index a nil value (global 'HUD')
[      script:esx_hud] stack traceback:
[      script:esx_hud] 	@esx_hud/server/main.lua:1: in main chunk
[    c-scripting-core] Failed to load script server/main.lua.
[      script:esx_hud] Error loading script server/mileage.lua in resource esx_hud: @esx_hud/server/mileage.lua:4: attempt to index a nil value (global 'HUD')
[      script:esx_hud] stack traceback:
[      script:esx_hud] 	@esx_hud/server/mileage.lua:4: in main chunk
[    c-scripting-core] Failed to load script server/mileage.lua.

**Comment by silez** [comment]
Yes, there is a missing }

```
HUD = {}
HUD.Data = {
    OnlinePlayers = 0,
    Weapon = {},
    Money = {}
}
```

This is what it should looks like and then you are good to go

**Comment by Rav3n95** [comment]
Fixed

**Comment by krasher023** [comment]
yep i will pr now

**Comment by krasher023** [comment]
oh nice :P i will close the post
