### ISSUE TITLE
 Resource are not built, please download the release version

### ISSUE THREAD

**Issue by Barbarians-eleven** [esx-framework/esx_hud#14]
I get this message when i start the actual version with no config.
Thanks,
Philous

**Comment by Rav3n95** [comment]
Did you downloaded the release version?

**Comment by EXHUN** [comment]
I also have this problem. How to download the release version?

**Comment by Rav3n95** [comment]
https://github.com/esx-framework/esx_hud/releases/download/v1.0.9/esx_hud.zip

**Comment by EXHUN** [comment]
thank you !
