### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by SamBradley123** [esx-framework/esx_hud#28]
Good morning,
since there is no translation for the HTML part (NUI), an error is displayed.

Would it be possible to fix this?
![image](https://user-images.githubusercontent.com/69010639/226640152-1fed3157-7be7-4a95-9b68-c1480aa06bb8.png)

**Comment by Rav3n95** [comment]
Make one

**Comment by Gellipapa** [comment]
Hi! @SamBradley123 You can add web/src/assets/translate.json. You should full source code and add your FR lang and you need rebuild all files.

Build process:
- Open web folder in terminal
- Type and run this command **npm i**
- After this runned type this command **npm run build**
- Done
