### ISSUE TITLE
Create esx_hud ui Locales

### ISSUE THREAD

**Issue by TheFantomas** [esx-framework/esx_hud#30]
In my opinion and the opinions of the testers, it would be good to add the possibility to translate ui in locales.

Like this in lua:

```lua
Locales["en"] = {
    ui_something = 'Something',
}
```

**Comment by Gellipapa** [comment]
https://github.com/esx-framework/esx_hud/blob/main/web/src/assets/translate.json

You can change translation here. When I did it I did it this way to separate the LUA and WEB parts. I think this is good way.

**Comment by TheFantomas** [comment]
> https://github.com/esx-framework/esx_hud/blob/main/web/src/assets/translate.json
> 
> You can change translation here. When I did it I did it this way to separate the LUA and WEB parts. I think this is good solution.

Beauty. Maybe I should write it somewhere in the readme because it's quite difficult to search for it this way :D

**Comment by Gellipapa** [comment]
I think we should add it to config.lua where we can change the lang, add a new comment and specify the relative path.

**Comment by TheFantomas** [comment]
> I think we should add it to config.lua where we can change the lang, add a new comment and specify the relative path.

That's not a bad idea at all. Will you do it? You can immediately release another release. Because there will also be some localizations from the past, I think :D

**Comment by Gellipapa** [comment]
Of course I'll write it in, but when #29  it's done.
