### ISSUE TITLE
Handling air vehicles

### ISSUE THREAD

**Issue by lexinor** [esx-framework/esx_hud#34]
Would be nice improvment to handle air vehicles by removing the speedo, removing turn signals (sound and actions) while in the air. Maybe more stuff can be adapted for air vehicles

**Comment by Gellipapa** [comment]
Hi! @lexinor Thank you for your message. Could you describe in a little more detail what you mean?

**Comment by lexinor** [comment]
> Hi! @lexinor Thank you for your message. Could you describe in a little more detail what you mean?

You can use turn signals while in an airplane which is not great and also It would be a nice improvment to add a proper speedo while in air vehicles that includes altitude

**Comment by Gellipapa** [comment]
We have reworked the speedo when you are in AIR vehicle but we didn't do gta 5 2.0 air vehicles hud, index usage can be a bug yes.

**Comment by lexinor** [comment]
> We have reworked the speedo when you are in AIR vehicle but we didn't do gta 5 2.0 air vehicles hud, index usage can be a bug yes.

Ok ok, didn't use it since that issue so
