### ISSUE TITLE
Add  seatbelt

### ISSUE THREAD

**Issue by JancsiOfficial** [esx-framework/esx_hud#35]
Add a seatbelt. Function: if the player is not buckled up, he will be thrown out of the car.

**Comment by Slewog** [comment]
With an export to check if the player is belt or not in a car to disabled seat changement from a menu

**Comment by Gellipapa** [comment]
@JancsiOfficial Hi! We not seatbelt featuret will be added to esx_hud a separate script will be created for this and will work with esx_hud using an export. 

Our goal is that the HUD should only display data visually, not contain complicated logic.
