### ISSUE TITLE
dont save correctly

### ISSUE THREAD

**Issue by Bobbbe** [esx-framework/esx_hud#38]
Hello, I love this hud, it's new, nice interface and simple :). I send you a link directing you to the esx_garage because I believe that the problem comes from either one or the other, if you have a chance to look.

https://github.com/esx-framework/esx_garage/issues/11

**Comment by Gellipapa** [comment]
@Rav3n95

**Comment by Gellipapa** [comment]
Hi! @Bobbbe 
Thank you for report issue. 
I tested works perfectly.
HUD use fuel system: LegacyFuel and ox_fuel, if you have custom fuel system you can add client/vehicle/fuel.lua in file.
I couldn't reproduce the error could you describe in more detail what you did?

What I did was I took a car and waited 5 minutes even went to the mileage and calculated the database value * 1.6 and it came out and I saw the result on the HUD, so it worked.

**Comment by Bobbbe** [comment]
I use oxyfuel, esx_garage and esx_hud! but I put in km/h in the options of the hud. I only replaced the esx_vehicleshop for the scrip (ox lib vehicleshop by mikigoalie) in the showcase section of the discord but I'll try to reinstall it with the basic options and I'll get back to you with more precision. thank you for your answers.

**Comment by Gellipapa** [comment]
@Bobbbe Hi! What's up? Works?
