### ISSUE TITLE
Second job in HUD

### ISSUE THREAD

**Issue by Edvesse** [esx-framework/esx_hud#47]
Hello,

Would it be possible to add below the first job, the same thing for a second job? I tried to add in all the files including the JS, job2 each time, but it didn't add me the line below the existing job. 

Thanks in advance.

**Comment by Gellipapa** [comment]
Hi! Sorry i don't understand your question. ESX don't support "multijob" or what do you mean?

**Comment by Edvesse** [comment]
Hey, 

Sorry, i want to know if it's possible to add a second job below the first job on HUD ? Because my extended are write with 2 jobs, and I would like it to be visible as the first on HUD

**Comment by Gellipapa** [comment]
@Edvesse Hi! If you want you can do it, but we don't support it because ESX doesn't have a "multijob" feature so we can't help you with that. We only try to provide things that are closely related to the framework.

**Comment by Edvesse** [comment]
I might be able to add it, now what I can't do, it is edit the JS files which are hard to read, do you think you can help me with that?

**Comment by Gellipapa** [comment]
@Edvesse You should download source - code in github not a release version. After you can run this command `npm i` in web folder, after run this command `npm run start` and now you can host web app. You can edit all web code in web/src folder but we writted in Solid JS if you don't have experience modern frontend frameworks you can't do this.

**Comment by Edvesse** [comment]
Very well, I will try to do it, thank you very much for your help!
