### ISSUE TITLE
Error message console with cycles

### ISSUE THREAD

**Issue by Edvesse** [esx-framework/esx_hud#48]
Hello,

When I get off my bike, I have this problem: 

[      script:esx_hud] SCRIPT ERROR: @esx_hud/server/mileage.lua:57: attempt to index a nil value (field '?')
[      script:esx_hud] > Update (@esx_hud/server/mileage.lua:57)
[      script:esx_hud] > handler (@esx_hud/server/mileage.lua:86)

The line are : self.Data[plate].mileage = mileage
On function Mileage:Update(plate, mileage, playerId, kmh

Can you help me ? Because sometimes this also happens to vehicles, quite rarely but it happens

Thanks you

**Comment by Edvesse** [comment]
Any solution please?

**Comment by Gellipapa** [comment]
@Edvesse Thank you for report, next release fixed this problem.
