### ISSUE TITLE
Health

### ISSUE THREAD

**Issue by TugaPowerROM** [esx-framework/esx_hud#49]
Having inconsistent health, when die, healt bar its still half. Any idea ?

![imagem](https://github.com/esx-framework/esx_hud/assets/9769460/9529d2e3-4019-4f4c-a911-a23fb81b06a5)

**Comment by TugaPowerROM** [comment]
Its just health that its reporting wrong values, thirst and hunger its consistent whith the actual values.

**Comment by Gellipapa** [comment]
@TugaPowerROM Thank you for report issue. @Rav3n95  can you check player HP calculated?

**Comment by Gellipapa** [comment]
@TugaPowerROM  Thank you for report this problem, next release fixed this problem.
