### ISSUE TITLE
Speedometer bugs and Mileage don't save

### ISSUE THREAD

**Issue by Antykors** [esx-framework/esx_hud#5]
Hello,

First problem : 
On random vehicle (import, sport, classic,sedan, etc...), speedometer disappears and only solution is disconect and reconnect.

Second problem :
Mileage don't save when i cut engine or i get out my car. And at the moment, mileage save for no reason...

Can you help me ?

Thanks

**Comment by Gellipapa** [comment]
Hi! @Antykors Thank you for report issue. 

Can you describe exactly what you do to reproduce these errors? 

1. problem: Only the bicycle is disabled in the speedo display.  So no matter what car you have, they should all have speedo.

Did you download the release version?

**Comment by Gellipapa** [comment]
@Rav3n95 will check.

**Comment by Antykors** [comment]
Hello,

No on all vehicle for speedo. But itry update ;)

And mileage save but when ? It's totaly random for me. One time save, one time don't save.

**Comment by Rav3n95** [comment]
It's going to be rewritten. I hade to change one thing, broke the whole millage system

**Comment by Antykors** [comment]
> It's going to be rewritten. I hade to change one thing, broke the whole millage system

Ok thx, but i have same problem for vehicle speedo. Random time speedo is invisible and when i restart, speedo spawn :P

**Comment by Antykors** [comment]
> > 
> 
> Thats fixed, only problem now its the milage

I have Last release but i have same problem for speedo. And its not on bike, i have problem at random time on car same.

**Comment by Rav3n95** [comment]
The one i updated like a hour ago?

**Comment by Antykors** [comment]
> It's not a relese version, you have to download the code and build it yourself

Yes i have build your code, but ramdom time speedo it's not on screen 

![image](https://user-images.githubusercontent.com/43018931/214827907-ddfa4362-52dd-426b-ab05-1af4c4dec028.png)

**Comment by Rav3n95** [comment]
When did you download it last time?

**Comment by Gellipapa** [comment]
> > It's not a relese version, you have to download the code and build it yourself
> 
> Yes i have build your code, but ramdom time speedo it's not on screen
> 
> ![image](https://user-images.githubusercontent.com/43018931/214827907-ddfa4362-52dd-426b-ab05-1af4c4dec028.png)

Hi! You should updated your es_extended in dev branch. This is dependency.

**Comment by Antykors** [comment]
> > > It's not a relese version, you have to download the code and build it yourself
> > 
> > 
> > Yes i have build your code, but ramdom time speedo it's not on screen
> > ![image](https://user-images.githubusercontent.com/43018931/214827907-ddfa4362-52dd-426b-ab05-1af4c4dec028.png)
> 
> Hi! You should updated your es_extended in dev branch. This is dependency.



> > > It's not a relese version, you have to download the code and build it yourself
> > 
> > 
> > Yes i have build your code, but ramdom time speedo it's not on screen
> > ![image](https://user-images.githubusercontent.com/43018931/214827907-ddfa4362-52dd-426b-ab05-1af4c4dec028.png)
> 
> Hi! You should updated your es_extended in dev branch. This is dependency.

You know what commit? I have a modified version of extended I can't update it completely

**Comment by Gellipapa** [comment]
@Antykors Hi! Yes this is commit, @Rav3n95 add lot of handler in es_extended core. esx_hud use these handlers.

**Comment by Rav3n95** [comment]
Should be fixed now
