### ISSUE TITLE
Helicopter speedometer and status bug

### ISSUE THREAD

**Issue by JancsiOfficial** [esx-framework/esx_hud#52]
Helicopter speedometer bug and sometimes I dead when the heart circle is full
![image](https://github.com/esx-framework/esx_hud/assets/123206097/5aef4cf1-6118-41ec-97b6-1d7d1ab9a910)

**Comment by Gellipapa** [comment]
@JancsiOfficial Fixed, please download latest version (v1.4.0). Thank you for report issue.
