### ISSUE TITLE
Default Speedo

### ISSUE THREAD

**Issue by 0xj0n1** [esx-framework/esx_hud#53]
Since I don't need the speedo from this hud, I tried to disable it in the config.lua. This only disabled the "main" speedo, but now I got this speedometer and I don't know how to get rid of it

**Comment by 0xj0n1** [comment]
![image](https://github.com/esx-framework/esx_hud/assets/78429664/c928147a-38c7-458c-9544-46af8dbae7bf)

**Comment by thesysadmindev** [comment]
This is not an issue with esx_hud. That's the HUD from LegacyFuel. Set `Config.EnableHUD` to false in config.lua.

**Comment by 0xj0n1** [comment]
thx
