### ISSUE TITLE
seatbelt keybind

### ISSUE THREAD

**Issue by Vincentbebeer** [esx-framework/esx_hud#70]
hey i cant find the keybind for the seatbelt can someone help me pls

**Comment by Arctos2win** [comment]
hey, it seems like esx_cruisecontrol ( the resource that is used to handle the keybind for the seatbelt ) is not in 
the esx recipe this will be added asap. you can resolve this issue yourself by downloading esx_cruisecontrol 
https://github.com/esx-framework/esx_cruisecontrol. 
thanks for reporting this issue.

**Comment by TheFantomas** [comment]
> hey i cant find the keybind for the seatbelt can someone help me pls

**Hello,**
As Arctos said, this will probably be the mistake. This has already been corrected. You only need to download the script.

Recipe prs reference:
https://github.com/esx-framework/esx-recipes/commit/92dfd46c2dc5f45570ca3a149e1cd59c7c9db363
https://github.com/esx-framework/esx-recipes/commit/bd7b5c59f752bebe76d85bbac8ea156d0bacec48

Best regards and have a nice day
**Fantík**
