### ISSUE TITLE
Dollar to euro 

### ISSUE THREAD

**Issue by Kerstman114** [esx-framework/esx_hud#71]
Hello!

How do you change the dollar sign to a euro sign? I can not find it.

**Comment by Gellipapa** [comment]
@Kerstman114 Hi! You should download source code, and open this file and you can change dollar to euro, after you need rebuild full app. 
https://github.com/esx-framework/esx_hud/blob/main/web/src/assets/Components/InfoHud.jsx#L80

**Comment by Kerstman114** [comment]
Ok, i found it. But how to rebuild the full app?

**Comment by Gellipapa** [comment]
> Ok, i found it. But how to rebuild the full app?

You should open web folder in terminal(cmd) and type this command "npm install" after this done type this command "npm run build" if done you need restart your scripts and works.

**Comment by Kerstman114** [comment]
Thank you for your support!! It works.

**Comment by Gellipapa** [comment]
> Thank you for your support!! It works.

You're welcome. 😄
