### ISSUE TITLE
Position and Icons of UI Elements

### ISSUE THREAD

**Issue by feanor5555** [esx-framework/esx_hud#73]
where can i set the position and icons for UI Elements?  some elements are over the minimap [screenshot](https://imgur.com/GZi05CL)

**Comment by Whomsky** [comment]
Wondering the same

**Comment by Gellipapa** [comment]
Hi! Currently there is no way to do this, unless you download the full source code and rebuild it yourself. The other option is that there is a switch in the settings that allows you to display the hud rounds side by side.

**Comment by Gellipapa** [comment]
![image](https://github.com/esx-framework/esx_hud/assets/22717950/a0310f9c-7643-469d-952e-6b5568aa5b6c)
