### ISSUE TITLE
Weapon UI shows in Photo App

### ISSUE THREAD

**Issue by bennimedia** [esx-framework/esx_hud#77]
When I open the Photos app on the phone, the interface shows me the weapons UI. Even if I don't own or have drawn a weapon

![image](https://github.com/esx-framework/esx_hud/assets/85938749/cf829610-deda-4230-be8d-a88eaddd6780)

**Comment by Gellipapa** [comment]
@bennimedia Hi! Phone is a killer device :) Joking aside, we will look into and fix the problem in the near future.

**Comment by Gellipapa** [comment]
Hi! I fixed please download latest version and retest. Thank you for report issue.
