### ISSUE TITLE
Cant find keybinds for hazard lights

### ISSUE THREAD

**Issue by NicholasS-dev** [esx-framework/esx_hud#92]
no where in the files have I been able to lovcate its keybind, being it bound v which is also change view is very annoying.

**Comment by Gellipapa** [comment]
@NicholasS-dev Hi! What do you mean "hazard lights"? There is no such logic in ESX hud. If you want to set the belt or cruise control keys, you can find it in the esx_cruisecontrol(https://github.com/esx-framework/esx_cruisecontrol) script.
